### ISSUE TITLE
Add Link Shell Extension to Invaluable Software

### ISSUE THREAD

**Issue by LB--** [orlp/dev-on-windows#1]
I find [Link Shell Extension](http://schinagl.priv.at/nt/hardlinkshellext/linkshellextension.html) to be incredibly useful for creating symbolic links and hard links (and other kinds) without having to resort to Windows' ugly command line tools.

**Comment by orlp** [comment]
I have never used that tool, so it would be hard for me to recommend it to others. To be fair, I rarely use symlinks on Windows, but when I do I usually have no problems with `mklink`.

So for now I'm declining this, but if in the future I will use a symlink I will try to evaluate this tool fairly.
