### ISSUE TITLE
update-core doesn't appear to do anything

### ISSUE THREAD

**Issue by carlca** [orlp/dev-on-windows#2]
I downloaded  ```msys2-x86_64-latest.exe``` 
I then issued the ```pacman -Sy msys2-launcher-git``` command which seemed to complete OK.
I then issued the ```update-core``` command, received the message ```bash: update-core: command not found```

What now?

**Comment by orlp** [comment]
It appears that `update-core` is now implemented in `pacman`. I have to update the guide.

**Comment by carlca** [comment]
Thanks! No problem. 3 minute response time, I'm impressed!

**Comment by orlp** [comment]
@carlca Guide is updated. Response time is coincidence ^^
