### ISSUE TITLE
How to add PATHs properly

### ISSUE THREAD

**Issue by carlca** [orlp/dev-on-windows#3]
You say in your instructions ```My recommendation is to inherit the path for the MinGW32/64 environments, but keeping the MSYS environment pure.```

How do you separately control the PATHs in the different environments?

**Comment by orlp** [comment]
Read the rest of the paragraph.

**Comment by carlca** [comment]
OK. Got it, I was expecting to have to change .BASHRC or .BASH_PROFILE or something similar. Thanks.
